/* 오류 메시지 */
const ERROR_PREFIX = '[ERROR] ';

export const ERROR_MESSAGE = {
  NOT_END_WITH_SEPARATOR: ERROR_PREFIX + '입력은 반드시 숫자로 끝나야 합니다.',
  NOT_ALLOWED_NEGATIVE: ERROR_PREFIX + '음수는 계산할 수 없습니다.',
  NOT_ALLOWED_NAN: ERROR_PREFIX + '입력값을 다시 확인해주세요.',
  ONLY_ENTER_INTEGER: ERROR_PREFIX + '숫자는 정수로만 입력해야 합니다.',
  CUSTOM_SEPARATOR_EMPTY: ERROR_PREFIX + '커스텀 구분자가 비어 있습니다.',
  CUSTOM_SEPARATOR_NOT_ALLOWED_NUMBER: ERROR_PREFIX + '커스텀 구분자는 숫자가 될 수 없습니다.',
  ONLY_ALLOWED_DECIMAL: ERROR_PREFIX + '숫자는 10진수로 입력해야 합니다.',
};

/* 메시지 유형 */
export const PASS = '';
export const NOT_END_WITH_SEPARATOR = 'NOT_END_WITH_SEPARATOR';
export const NOT_ALLOWED_NEGATIVE = 'NOT_ALLOWED_NEGATIVE';
export const NOT_ALLOWED_NAN = 'NOT_ALLOWED_NAN';
export const ONLY_ENTER_INTEGER = 'ONLY_ENTER_INTEGER';
export const CUSTOM_SEPARATOR_EMPTY = 'CUSTOM_SEPARATOR_EMPTY';
export const CUSTOM_SEPARATOR_NOT_ALLOWED_NUMBER = 'CUSTOM_SEPARATOR_NOT_ALLOWED_NUMBER';
export const ONLY_ALLOWED_DECIMAL = 'ONLY_ALLOWED_DECIMAL';