/* 오류 메시지 */
export const ERROR_MESSAGE = '[ERROR]';

/* 메시지 유형 */
export const PASS = '';
export const NOT_END_WITH_NUMBER = 'NOT_END_WITH_NUMBER';
export const NOT_ALLOWED_NEGATIVE = 'NOT_ALLOWED_NEGATIVE';
export const NOT_ALLOWED_NAN = 'NOT_ALLOWED_NAN';
export const ONLY_ENTER_INTEGER = 'ONLY_ENTER_INTEGER';
export const CUSTOM_SEPARATOR_EMPTY = 'CUSTOM_SEPARATOR_EMPTY';
export const CUSTOM_SEPARATOR_NUMBER = 'CUSTOM_SEPARATOR_NUMBER';
export const ONLY_ALLOWED_DECIMAL = 'ONLY_ALLOWED_DECIMAL';